# Generate the SQL query to show the ages when each task was completed in a
# long-format table

library(dplyr)
library(glue)

# We want to get the age and test completion dates from these tables
tasks_to_add <- tibble::tribble(
  ~task_name,       ~table,
  "Blending",       "l2t.Blending_Summary",
  "BRIEF",          "l2t.BRIEF",
  "CTOPP_Blending", "l2t.CTOPP_Blending",
  "CTOPP_Elision",  "l2t.CTOPP_Elision",
  "CTOPP_Memory",   "l2t.CTOPP_Memory",
  "DELV_Risk",      "l2t.DELV_Risk",
  "FruitStroop",    "l2t.FruitStroop",
  "GFTA",           "l2t.GFTA",
  "KBIT",           "l2t.KBIT",
  "LENA",           "l2t.LENA_Averages",
  "MinPair",        "l2t.MinPair_Aggregate",
  "PPVT",           "l2t.PPVT",
  "Rhyming",        "l2t.Rhyming_Aggregate",
  "SAILS",          "l2t.SAILS_Aggregate",
  "VerbalFluency",  "l2t.VerbalFluency"
)


# We consistently name columns TASK_Age and TASK_Completion in each task's table
# , so given a task name we can figure out the the name of the two columns.
create_task_row <- function(task_name, table_name){
  data_frame(
    task = task_name,
    completion = paste0(task_name, "_Completion"),
    age = paste0(task_name, "_Age"),
    table = table_name)
}

task_variables <- purrr::map2_df(
  tasks_to_add$task_name,
  tasks_to_add$table,
  create_task_row)
task_variables

# To generate the SQL query, we are going to convert each row of this table to
# SQL statement that gives a table with a task name, age and date of completion.

# First, we create an initial set of rows using the EVT.
base_chunk <- "
-- Code generated by `create_age_query.R`
-- Edit that file instead

create or replace algorithm = undefined view l2t.Task_Ages as
  select
    Study,
    ResearchID,
    \"EVT\" as Task,
    EVT_Completion as TaskDate,
    EVT_Age as TaskAge
  from
    l2t.EVT"

# For each of the tasks in the dataframe, we fill out this templated string to
# create a query for each task.
template <- "
-- rows for batch
  union all
    select
      Study,
      ResearchID,
      \"{task}\" as Task,
      {completion} as TaskDate,
      {age} as TaskAge
    from
      {table}
"

# Fill out the template for each table and combine into a single string
string <- glue_data(task_variables, template) %>%
  glue::collapse(sep = "\n") %>%
  stringr::str_replace_all("-- rows for batch\n", "")

# Add first chunk on top
query <- glue::collapse(c(base_chunk, string), sep = "\n")
cat(query)

writeLines(query, "./inst/views/ages.sql")
